version: '3.5'

services:
   zmm:
    image: store/softwareag/mlw-zmm:10.5 
    container_name: zmm
    command: /bin/bash -c "dotnet App.dll"
    working_dir: /publish
    volumes:
      - shared-content:/ZMOD
      - ./Code:/ZMOD/Code
      - ./Data:/ZMOD/Data
      - ./Models:/ZMOD/Models 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:

      - "7008:7008"
      - "7007:7007"  
    expose:
       - "7008"
       - "7007"


    restart: always

    networks:
      test:
        ipv4_address: '172.20.0.3'


networks:
  test:
    name: global-zmod-net
    ipam:
      driver: default
      config:
       - subnet: 172.20.0.0/24
volumes:
  shared-content:


